/**
 * @file pdfGenerator.js
 * @description Generates a clean PDF tax summary from a FullTaxCalculation result.
 *              Saves the PDF to a temp file and returns the path.
 *              The caller is responsible for deleting the file after use.
 *
 *              NDPR/NDPA Compliance:
 *              - The PDF never contains the user's phone number or any personal identifier.
 *              - No financial figures are logged at any point in this module.
 *              - The temp file must be deleted immediately after sending.
 * @author Kuditax Engineering
 * @updated 2026-03-28
 */

import PDFDocument from 'pdfkit';
import { createWriteStream } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { randomBytes } from 'crypto';
import { formatNaira } from '../utils/formatter.js';
import logger from '../utils/logger.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const TAX_YEAR = 2025;
const PDF_MARGIN        = 50;
// Bottom margin is larger than the others to carve out a reserved zone for the
// per-page footnote. PDFKit will auto-break before reaching this area so
// body content never overlaps the footnote.
const PDF_BOTTOM_MARGIN = 70;

// Font sizes
const FS_TITLE    = 18;
const FS_SUBTITLE = 9;
const FS_SECTION  = 11;
const FS_BODY     = 10;
const FS_FOOTNOTE = 7;

// Footnote appears at the absolute bottom of every page.
// Replaces the old in-body DISCLAIMER section so it is unobtrusive but always present.
const FOOTNOTE_TEXT =
  '⚠️  This document is a tax calculation summary for reference only. It is NOT an official ' +
  'tax return and cannot be submitted to the Nigeria Revenue Service (NRS) as a standalone document. ' +
  'Use these figures to complete your return at taxpromax.firs.gov.ng | Generated by Kuditax';

const NEXT_STEPS = [
  '1. Visit https://taxpromax.firs.gov.ng',
  '2. Log in with your TIN (click Register if this is your first time)',
  '3. Select File Returns → Personal Income Tax Annual Return',
  '4. Use the figures above to complete your return',
  '5. Pay via the Remita reference generated',
  '6. Download your receipt and tax clearance certificate',
];

// ---------------------------------------------------------------------------
// PDF Section Writers
// Each writer receives the document object and mutates it with its section.
// ---------------------------------------------------------------------------

/**
 * Writes the document title block: product name, subtitles, and generated date.
 *
 * @param {PDFKit.PDFDocument} doc
 */
function writeDocumentHeader(doc) {
  const generatedDate = new Date().toLocaleDateString('en-NG', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  doc.font('Helvetica-Bold').fontSize(FS_TITLE).text('KUDITAX TAX SUMMARY', { align: 'center' });
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(FS_SUBTITLE)
    .text('Personal Income Tax Summary — Tax Year 2025', { align: 'center' })
    .text('Reference document for filing Annual Return on TaxPro-Max', { align: 'center' });
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(FS_BODY)
    .text(`Generated: ${generatedDate}`, { align: 'center' });
  doc.moveDown(1.5);
}

/**
 * Writes a bold section header with a rule line underneath.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {string} title
 */
function writeSectionHeader(doc, title) {
  doc.font('Helvetica-Bold').fontSize(FS_SECTION).fillColor('black').text(title.toUpperCase());
  doc
    .moveTo(PDF_MARGIN, doc.y)
    .lineTo(doc.page.width - PDF_MARGIN, doc.y)
    .strokeColor('black')
    .lineWidth(1)
    .stroke();
  doc.moveDown(0.5);
}

/**
 * Writes a single label/value row in body font.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {string} label
 * @param {string} value
 */
function writeRow(doc, label, value) {
  doc.font('Helvetica').fontSize(FS_BODY).fillColor('black').text(`${label}: ${value}`);
}

/**
 * Writes the YOUR FILING DETAILS section with placeholder fields for all
 * officially required Nigerian personal income tax return information.
 * Users must complete these fields when filing on TaxPro-Max.
 *
 * The blank lines use underscores as visible placeholders so the user
 * can print and hand-fill the document before or during online filing.
 *
 * @param {PDFKit.PDFDocument} doc
 */
function writeFilingDetailsSection(doc) {
  writeSectionHeader(doc, 'Your Filing Details');

  const BLANK = '______________________';

  writeRow(doc, 'Full Legal Name',       BLANK);
  writeRow(doc, 'Tax Identification No', BLANK);
  writeRow(doc, 'Home Address',          BLANK);
  writeRow(doc, 'State of Residence',    BLANK);
  writeRow(doc, 'Employer Name',         `${BLANK}  (if employed)`);
  writeRow(doc, 'Employer Address',      `${BLANK}  (if employed)`);
  writeRow(doc, 'Assessment Period',     '1 January 2025 – 31 December 2025');
  doc.moveDown(0.6);

  // NDPA notice — inform the user what to have ready before starting on TaxPro-Max
  doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor('#b85c00')
    .text('⚠️  IMPORTANT: These fields are required when filing on TaxPro-Max.');
  doc.font('Helvetica').fontSize(FS_BODY).fillColor('black')
    .text('    Have the following ready before you begin:');

  const CHECKLIST = [
    "• Your TIN (get it free at jtb.gov.ng if you don't have one)",
    "• Your employer's full registered name and address",
    '• Your home address as registered with your state IRS',
    '• A valid means of identification (NIN or BVN for verification)',
  ];
  for (const item of CHECKLIST) {
    doc.font('Helvetica').fontSize(FS_BODY).fillColor('black').text(`    ${item}`);
  }

  doc.moveDown(1);
}

/**
 * Writes the INCOME SUMMARY section.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {import('./taxCalculator.js').FullTaxCalculation} result
 */
function writeIncomeSummary(doc, result) {
  writeSectionHeader(doc, 'Income Summary');
  writeRow(doc, 'Annual Gross Income', formatNaira(result.grossIncome));
  doc.moveDown(1);
}

/**
 * Writes the DEDUCTIONS & RELIEFS section.
 * Only shows deduction lines that are non-zero to keep the PDF uncluttered.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {import('./taxCalculator.js').FullTaxCalculation} result
 */
function writeDeductionsSection(doc, result) {
  writeSectionHeader(doc, 'Deductions & Reliefs');
  if (result.pensionDeduction > 0)       writeRow(doc, 'Pension Contribution', formatNaira(result.pensionDeduction));
  if (result.nhfDeduction > 0)           writeRow(doc, 'NHF Contribution', formatNaira(result.nhfDeduction));
  if (result.rentRelief > 0)             writeRow(doc, 'Rent Relief', formatNaira(result.rentRelief));
  if (result.lifeAssuranceDeduction > 0) writeRow(doc, 'Life Assurance', formatNaira(result.lifeAssuranceDeduction));
  doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor('black')
    .text(`Total Deductions: ${formatNaira(result.totalDeductions)}`);
  doc.moveDown(1);
}

/**
 * Writes the TAX CALCULATION section including the band-by-band breakdown.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {import('./taxCalculator.js').FullTaxCalculation} result
 */
function writeTaxCalculation(doc, result) {
  writeSectionHeader(doc, `Tax Calculation (Nigeria Tax Act ${TAX_YEAR})`);
  writeRow(doc, 'Chargeable Income', formatNaira(result.chargeableIncome));
  doc.moveDown(0.5);

  doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor('black').text('Band Breakdown:');
  doc.font('Helvetica').fontSize(FS_BODY).fillColor('black');

  for (const band of result.tax.breakdown) {
    const rateLabel = `${Math.round(band.rate * 100)}%`;
    doc.text(`  ${band.label}: ${formatNaira(band.taxableInBand)} @ ${rateLabel} = ${formatNaira(band.taxInBand)}`);
  }
  doc.moveDown(1);
}

/**
 * Writes the RESULT section: annual tax, monthly PAYE, effective rate.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {import('./taxCalculator.js').FullTaxCalculation} result
 */
function writeResultSection(doc, result) {
  writeSectionHeader(doc, 'Result');

  // Effective tax rate = total tax ÷ gross income (meaningful for the taxpayer)
  const effectiveRate = result.grossIncome > 0
    ? ((result.tax.totalTax / result.grossIncome) * 100).toFixed(1)
    : '0.0';

  doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor('black')
    .text(`Annual Tax Owed: ${formatNaira(result.tax.totalTax)}`);
  writeRow(doc, 'Monthly PAYE', formatNaira(result.tax.monthlyTax));
  writeRow(doc, 'Effective Tax Rate', `${effectiveRate}%`);
  doc.moveDown(1);
}

/**
 * Writes the NEXT STEPS section with the TaxPro-Max filing guide.
 *
 * @param {PDFKit.PDFDocument} doc
 */
function writeNextStepsSection(doc) {
  writeSectionHeader(doc, 'Next Steps — How to File on TaxPro-Max');
  doc.font('Helvetica').fontSize(FS_BODY).fillColor('black');
  for (const step of NEXT_STEPS) {
    doc.text(step);
  }
  doc.moveDown(1);
}

/**
 * Writes the DECLARATION section with a signature and date line.
 * Provides a formal taxpayer declaration and a space to sign before
 * the document is presented to or used alongside a FIRS submission.
 *
 * @param {PDFKit.PDFDocument} doc
 */
function writeDeclarationSection(doc) {
  writeSectionHeader(doc, 'Declaration');

  doc.font('Helvetica').fontSize(FS_BODY).fillColor('black')
    .text(
      'I declare that the information provided in this summary is true and accurate ' +
      'to the best of my knowledge.'
    );
  doc.moveDown(1);

  doc.font('Helvetica').fontSize(FS_BODY).fillColor('black')
    .text('Signature: ______________________   Date: ________________');
  doc.moveDown(0.5);

  doc.font('Helvetica').fontSize(FS_BODY).fillColor('black')
    .text(
      'This summary was prepared using Kuditax based on information provided by the taxpayer. ' +
      'It should be verified before submission.'
    );
  doc.moveDown(0.5);

  doc
    .moveTo(PDF_MARGIN, doc.y)
    .lineTo(doc.page.width - PDF_MARGIN, doc.y)
    .strokeColor('black')
    .lineWidth(1)
    .stroke();
  doc.moveDown(1);
}

/**
 * Writes the disclaimer footnote at the absolute bottom of the current page.
 * Uses absolute Y positioning so it is always anchored to the page bottom
 * and never interferes with flowing body content.
 *
 * Called via PDFKit's 'pageAdded' event for every page after the first,
 * and manually for page 1 after all content has been written.
 *
 * After writing, the text cursor is reset to its pre-call position so that
 * the 'pageAdded' handler does not displace subsequent section writers.
 *
 * @param {PDFKit.PDFDocument} doc
 */
function writePageFootnote(doc) {
  // Anchor the footnote inside the bottom margin zone, safely below the content area.
  // Content stops at page.height - PDF_BOTTOM_MARGIN (≈ 772 pt on A4).
  // Footnote starts at page.height - PDF_BOTTOM_MARGIN + 12 (≈ 784 pt) — 12 pt gap.
  const footnoteY = doc.page.height - PDF_BOTTOM_MARGIN + 12;

  // Save cursor so the pageAdded handler can restore it after writing the footnote
  const savedX = doc.x;
  const savedY = doc.y;

  doc.save();
  // Thin grey separator line above the footnote text
  doc
    .moveTo(PDF_MARGIN, footnoteY - 4)
    .lineTo(doc.page.width - PDF_MARGIN, footnoteY - 4)
    .strokeColor('#aaaaaa')
    .lineWidth(0.5)
    .stroke();
  doc.font('Helvetica').fontSize(FS_FOOTNOTE).fillColor('#888888')
    .text(FOOTNOTE_TEXT, PDF_MARGIN, footnoteY, {
      width: doc.page.width - PDF_MARGIN * 2,
      align: 'center',
    });
  doc.restore();

  // Restore cursor position so content on new pages starts at the correct Y
  doc.x = savedX;
  doc.y = savedY;
}

// ---------------------------------------------------------------------------
// Temp File Helpers
// ---------------------------------------------------------------------------

/**
 * Creates a unique temp file path for the PDF.
 * Uses a random hex suffix to prevent collisions under concurrent load.
 * The file name does NOT include any user identifier.
 *
 * @returns {string} Absolute path to the temp file
 */
function createTempFilePath() {
  const suffix = randomBytes(8).toString('hex');
  return join(tmpdir(), `kuditax-${suffix}.pdf`);
}

/**
 * Pipes the PDFDocument to a write stream and resolves when the file is fully written.
 *
 * @param {PDFKit.PDFDocument} doc - Finalised PDFDocument (doc.end() must not yet have been called)
 * @param {string} filePath - Absolute path of the output file
 * @returns {Promise<void>}
 */
function savePdfToFile(doc, filePath) {
  return new Promise((resolve, reject) => {
    const stream = createWriteStream(filePath);
    stream.on('finish', resolve);
    stream.on('error', reject);
    doc.pipe(stream);
    doc.end();
  });
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates a PDF tax summary from a full tax calculation result.
 * Saves the PDF to a unique temp file and returns the file path.
 *
 * The caller MUST delete the file after use. No user PII is written to the PDF.
 *
 * @param {import('./taxCalculator.js').FullTaxCalculation} taxResult - Full calculation result
 * @param {string} [language='en'] - User's language code (reserved for future i18n of PDF)
 * @returns {Promise<string>} Absolute path to the generated PDF temp file
 * @throws {Error} If PDF generation fails (caller should handle and send text fallback)
 *
 * @example
 * const filePath = await generateTaxSummaryPdf(result, 'en');
 * // ... send filePath via WhatsApp ...
 * await unlink(filePath); // caller cleans up
 */
async function generateTaxSummaryPdf(taxResult, language = 'en') {
  const filePath = createTempFilePath();

  logger.info('Generating tax summary PDF', { language });

  const doc = new PDFDocument({
    // Use asymmetric margins: the larger bottom margin reserves space for the per-page
    // footnote, preventing PDFKit from flowing content into that zone.
    margins: { top: PDF_MARGIN, bottom: PDF_BOTTOM_MARGIN, left: PDF_MARGIN, right: PDF_MARGIN },
    size: 'A4',
  });

  // Attach the footnote to every new page PDFKit adds (pages 2, 3, …).
  // The cursor is reset inside writePageFootnote so content continues from the top.
  doc.on('pageAdded', () => writePageFootnote(doc));

  writeDocumentHeader(doc);
  writeFilingDetailsSection(doc);
  writeIncomeSummary(doc, taxResult);
  writeDeductionsSection(doc, taxResult);
  writeTaxCalculation(doc, taxResult);
  writeResultSection(doc, taxResult);
  writeNextStepsSection(doc);
  writeDeclarationSection(doc);

  // Write the footnote on page 1 manually — the 'pageAdded' event does not fire
  // for the first page (PDFKit creates it synchronously in the constructor).
  writePageFootnote(doc);

  await savePdfToFile(doc, filePath);

  logger.info('Tax summary PDF generated successfully');
  return filePath;
}

export { generateTaxSummaryPdf };
