/**
 * @file pdfGenerator.js
 * @description Generates a clean PDF tax summary from a FullTaxCalculation result.
 *              Saves the PDF to a temp file and returns the path.
 *              The caller is responsible for deleting the file after use.
 *
 *              NDPR/NDPA Compliance:
 *              - The PDF never contains the user's phone number or any personal identifier.
 *              - No financial figures are logged at any point in this module.
 *              - The temp file must be deleted immediately after sending.
 * @author Kuditax Engineering
 * @updated 2026-03-28
 */

import PDFDocument from 'pdfkit';
import { createWriteStream } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { randomBytes } from 'crypto';
import { formatNaira } from '../utils/formatter.js';
import logger from '../utils/logger.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const TAX_YEAR = 2025;
const FILED_YEAR = 2026;
const PDF_MARGIN = 50;

// Font sizes
const FS_TITLE    = 18;
const FS_SECTION  = 11;
const FS_BODY     = 10;
const FS_FOOTER   = 8;

const FOOTER_TEXT     = 'Generated by Kuditax | For guidance only';
const DISCLAIMER_TEXT =
  'This is an estimate for guidance only. File officially at https://taxpromax.firs.gov.ng';

const NEXT_STEPS = [
  '1. Visit https://taxpromax.firs.gov.ng',
  '2. Log in with your TIN (click Register if this is your first time)',
  '3. Select File Returns → Personal Income Tax Annual Return',
  '4. Use the figures above to complete your return',
  '5. Pay via the Remita reference generated',
  '6. Download your receipt and tax clearance certificate',
];

// ---------------------------------------------------------------------------
// PDF Section Writers
// Each writer receives the document object and mutates it with its section.
// ---------------------------------------------------------------------------

/**
 * Writes the document title block: product name, generated date, tax year.
 *
 * @param {PDFKit.PDFDocument} doc
 */
function writeDocumentHeader(doc) {
  const generatedDate = new Date().toLocaleDateString('en-NG', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  doc.font('Helvetica-Bold').fontSize(FS_TITLE).text('KUDITAX TAX SUMMARY', { align: 'center' });
  doc.moveDown(0.5);
  doc.font('Helvetica').fontSize(FS_BODY)
    .text(`Generated: ${generatedDate}`, { align: 'center' })
    .text(`Tax Year: ${TAX_YEAR} (filed ${FILED_YEAR})`, { align: 'center' });
  doc.moveDown(1.5);
}

/**
 * Writes a bold section header with a rule line underneath.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {string} title
 */
function writeSectionHeader(doc, title) {
  doc.font('Helvetica-Bold').fontSize(FS_SECTION).text(title.toUpperCase());
  doc
    .moveTo(PDF_MARGIN, doc.y)
    .lineTo(doc.page.width - PDF_MARGIN, doc.y)
    .stroke();
  doc.moveDown(0.5);
}

/**
 * Writes a single label/value row in body font.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {string} label
 * @param {string} value
 */
function writeRow(doc, label, value) {
  doc.font('Helvetica').fontSize(FS_BODY).text(`${label}: ${value}`);
}

/**
 * Writes the INCOME SUMMARY section.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {import('./taxCalculator.js').FullTaxCalculation} result
 */
function writeIncomeSummary(doc, result) {
  writeSectionHeader(doc, 'Income Summary');
  writeRow(doc, 'Annual Gross Income', formatNaira(result.grossIncome));
  doc.moveDown(1);
}

/**
 * Writes the DEDUCTIONS & RELIEFS section.
 * Only shows deduction lines that are non-zero to keep the PDF uncluttered.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {import('./taxCalculator.js').FullTaxCalculation} result
 */
function writeDeductionsSection(doc, result) {
  writeSectionHeader(doc, 'Deductions & Reliefs');
  if (result.pensionDeduction > 0)       writeRow(doc, 'Pension Contribution', formatNaira(result.pensionDeduction));
  if (result.nhfDeduction > 0)           writeRow(doc, 'NHF Contribution', formatNaira(result.nhfDeduction));
  if (result.rentRelief > 0)             writeRow(doc, 'Rent Relief', formatNaira(result.rentRelief));
  if (result.lifeAssuranceDeduction > 0) writeRow(doc, 'Life Assurance', formatNaira(result.lifeAssuranceDeduction));
  doc.font('Helvetica-Bold').fontSize(FS_BODY)
    .text(`Total Deductions: ${formatNaira(result.totalDeductions)}`);
  doc.moveDown(1);
}

/**
 * Writes the TAX CALCULATION section including the band-by-band breakdown.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {import('./taxCalculator.js').FullTaxCalculation} result
 */
function writeTaxCalculation(doc, result) {
  writeSectionHeader(doc, `Tax Calculation (Nigeria Tax Act ${TAX_YEAR})`);
  writeRow(doc, 'Chargeable Income', formatNaira(result.chargeableIncome));
  doc.moveDown(0.5);

  doc.font('Helvetica-Bold').fontSize(FS_BODY).text('Band Breakdown:');
  doc.font('Helvetica').fontSize(FS_BODY);

  for (const band of result.tax.breakdown) {
    const rateLabel = `${Math.round(band.rate * 100)}%`;
    doc.text(`  ${band.label}: ${formatNaira(band.taxableInBand)} @ ${rateLabel} = ${formatNaira(band.taxInBand)}`);
  }
  doc.moveDown(1);
}

/**
 * Writes the RESULT section: annual tax, monthly PAYE, effective rate.
 *
 * @param {PDFKit.PDFDocument} doc
 * @param {import('./taxCalculator.js').FullTaxCalculation} result
 */
function writeResultSection(doc, result) {
  writeSectionHeader(doc, 'Result');

  // Effective tax rate = total tax ÷ gross income (meaningful for the taxpayer)
  const effectiveRate = result.grossIncome > 0
    ? ((result.tax.totalTax / result.grossIncome) * 100).toFixed(1)
    : '0.0';

  doc.font('Helvetica-Bold').fontSize(FS_BODY)
    .text(`Annual Tax Owed: ${formatNaira(result.tax.totalTax)}`);
  writeRow(doc, 'Monthly PAYE', formatNaira(result.tax.monthlyTax));
  writeRow(doc, 'Effective Tax Rate', `${effectiveRate}%`);
  doc.moveDown(1);
}

/**
 * Writes the DISCLAIMER section.
 *
 * @param {PDFKit.PDFDocument} doc
 */
function writeDisclaimerSection(doc) {
  writeSectionHeader(doc, 'Disclaimer');
  doc.font('Helvetica').fontSize(FS_BODY).text(DISCLAIMER_TEXT);
  doc.moveDown(1);
}

/**
 * Writes the NEXT STEPS section with the TaxPro-Max filing guide.
 *
 * @param {PDFKit.PDFDocument} doc
 */
function writeNextStepsSection(doc) {
  writeSectionHeader(doc, 'Next Steps — How to File on TaxPro-Max');
  doc.font('Helvetica').fontSize(FS_BODY);
  for (const step of NEXT_STEPS) {
    doc.text(step);
  }
  doc.moveDown(1);
}

/**
 * Writes the footer at the bottom of the last page.
 *
 * @param {PDFKit.PDFDocument} doc
 */
function writeFooter(doc) {
  doc
    .moveTo(PDF_MARGIN, doc.y)
    .lineTo(doc.page.width - PDF_MARGIN, doc.y)
    .stroke();
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(FS_FOOTER).fillColor('grey')
    .text(FOOTER_TEXT, { align: 'center' });
}

// ---------------------------------------------------------------------------
// Temp File Helpers
// ---------------------------------------------------------------------------

/**
 * Creates a unique temp file path for the PDF.
 * Uses a random hex suffix to prevent collisions under concurrent load.
 * The file name does NOT include any user identifier.
 *
 * @returns {string} Absolute path to the temp file
 */
function createTempFilePath() {
  const suffix = randomBytes(8).toString('hex');
  return join(tmpdir(), `kuditax-${suffix}.pdf`);
}

/**
 * Pipes the PDFDocument to a write stream and resolves when the file is fully written.
 *
 * @param {PDFKit.PDFDocument} doc - Finalised PDFDocument (doc.end() must not yet have been called)
 * @param {string} filePath - Absolute path of the output file
 * @returns {Promise<void>}
 */
function savePdfToFile(doc, filePath) {
  return new Promise((resolve, reject) => {
    const stream = createWriteStream(filePath);
    stream.on('finish', resolve);
    stream.on('error', reject);
    doc.pipe(stream);
    doc.end();
  });
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates a PDF tax summary from a full tax calculation result.
 * Saves the PDF to a unique temp file and returns the file path.
 *
 * The caller MUST delete the file after use. No user PII is written to the PDF.
 *
 * @param {import('./taxCalculator.js').FullTaxCalculation} taxResult - Full calculation result
 * @param {string} [language='en'] - User's language code (reserved for future i18n of PDF)
 * @returns {Promise<string>} Absolute path to the generated PDF temp file
 * @throws {Error} If PDF generation fails (caller should handle and send text fallback)
 *
 * @example
 * const filePath = await generateTaxSummaryPdf(result, 'en');
 * // ... send filePath via WhatsApp ...
 * await unlink(filePath); // caller cleans up
 */
async function generateTaxSummaryPdf(taxResult, language = 'en') {
  const filePath = createTempFilePath();

  logger.info('Generating tax summary PDF', { language });

  const doc = new PDFDocument({ margin: PDF_MARGIN, size: 'A4' });

  writeDocumentHeader(doc);
  writeIncomeSummary(doc, taxResult);
  writeDeductionsSection(doc, taxResult);
  writeTaxCalculation(doc, taxResult);
  writeResultSection(doc, taxResult);
  writeDisclaimerSection(doc);
  writeNextStepsSection(doc);
  writeFooter(doc);

  await savePdfToFile(doc, filePath);

  logger.info('Tax summary PDF generated successfully');
  return filePath;
}

export { generateTaxSummaryPdf };
